### ISSUE TITLE
Implement a Regression Neural Network module

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#22]
#### Description
Add a regression neural network module `nn_rg`

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

* `touvlo/supv/nn.py`
       + Existing module of classification neural network
* `test/test_nn.py`
       + Existing test suite for  classification neural network module

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Implement  regression neural network module as `touvlo/supv/nn_rg`
- [ ] Implement a test suite with test cases covering each routine/function in `touvlo/supv/nn_rg`  
- [ ] Document via pydoc each routine/function in `touvlo/supv/nn_rg`
- [ ] Configure `docs/source/supv.rst` to include the new module in the project docs
