### ISSUE TITLE
Implement a Support Vector Machine Classification module (Linear and Gaussian Kernels) 

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#24]
#### Description
Add a Support Vector Machine Classification module (Linear and Gaussian Kernels) to the package

#### Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

* `touvlo/supv/`
       + Where the Support Vector Machine Classification module belongs
* `test/supv/`
       + Where the Support Vector Machine Classification test suite belongs
* `/docs/source/supv.rst`
       + File to edit to add the module pydoc to the docs

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Implement  the Support Vector Machine Classification module
- [ ] Implement a test suite with test cases covering each routine/function in the module  
- [ ] Document via pydoc each routine/function in the module
- [ ] Configure `docs/source/supv.rst` to include the new module in the project docs
