### ISSUE TITLE
Add shuffling to Stochastic Gradient Descent 

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#36]
#### Description
Edit SGD to shuffle data before each inner loop

#### Files
* `touvlo/utils.py`
      + Location of SGD implementation
* `tests/test_utils.py`
      + Location of test cases for the SGD implementation

#### Tasks
- [ ] Add shuffle to  SGD
- [ ] Edit existing tests at `tests/test_utils.py` and if necessary add new ones
- [ ] Edit documentation if any function signature has been changed

**Comment by nightfox0909** [comment]
Id love to help, if nobody has taken it yet!
