### ISSUE TITLE
Add pylint testing environment

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#41]
#### Description
A new testing environment to be included in both tox and travis CI

#### Files
* `tox.ini` - tox configuration file
* `.travis.yml` - travis  configuration file
* `dev-requirements.txt` - travis  configuration file

#### Tasks
- [ ] Add pylint to dev requirements
- [ ] Configure tox to include a pylint testenv
- [ ] Configure travis to employ new pylint testenv 
- [ ] Conform existing code to pylint analysis
  + If necessary, add a configuration file for pylint
  + If you choose to ignore a rule please justify why

**Comment by enflo** [comment]
I'm working on the Issue. I have added pylint, with respect to the file pylintrc requires some special configuration?  Do you want any specific changes?

**Comment by Benardi** [comment]
> I'm working on the Issue. I have added pylint, with respect to the file pylintrc requires some special configuration? Do you want any specific changes?

Nothing in particular, just please make sure that the existing code conforms to the linting checks.
