### ISSUE TITLE
Add classes for existing Linear Regression implementations

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#46]
#### Description
Add classes to encapsulate existing Ridge and Unregularized Linear Regression implementations.

#### Files
* `touvlo/supv/lin_rg.py` - Existing linear regression module
* `tests/supv/test_lin_rg.py` - Test suite for linear regression module

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [x] Add classes for Ridge and Unregularized Linear Regression 
- [x] Add unit tests for new classes
- [x] Add documentation for new classes
