### ISSUE TITLE
Add computation graph based logistic regression 

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#51]
#### Description
Add a computation graph based logistic regression 

#### Files
* touvlo/supv/lgx_rg.py
* tests/supv/test_lgx_rg.py

#### Tasks
- [x] Implement a lgx_rg submodule using computation graph
 + Organize all lgx_rg modules to prevent naming clashes
- [x] Add documentations for implemented module
- [x] Add unit tests for implemented module
- [x] If necessary, reorganize existing modules to prevent that the calls to modules attributes are too deep: touvlo.X.Y.Z.W.attribute
