### ISSUE TITLE
Add Vectorized Neural Net module

### ISSUE THREAD

**Issue by Benardi** [Benardi/touvlo#53]
#### Description
Add Vectorized Neural Net module and reorganize Neural Net modules into a common sub-module.

#### Files
* `touvlo/nn_clsf.py`
* `touvlo/utils.py`
* `tests/test_nn_clsf.py`

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Add vectorized neural net module
- [ ] Add tests for new module
- [ ] Add documentation for new module
- [ ] Organize new module and existing nn module into a single submodule

Remember to use helpful labels and milestones. If you use the "help wanted" label, Code for America will [promote it widely](http://www.codeforamerica.org/geeks/civicissues).
